### PR TITLE
Rutger/fix user error trace

### LINKED ISSUE #32: Do not show error trace to the user
The bot currently is posting the full error context into a github comment. As an example see here: https://github.com/paritytech/substrate/pull/12723#issuecomment-1321700543

It should only post:
```
@bkchr ERROR: Error: Contributor did not properly post their account address.

Make sure the pull request description has: "{network} address: {address}".
```

### PR DESCRIPTION
**Pull request by parutger**
Fixes #32 by improving error handling

Changes localhost to 127.0.0.1 for IPv4 only localtest

Include dotenv config to fix local testing environment

### CODE REVIEW

**Review by rzadp — APPROVED** [review]

File: src/tip.ts [hunk 1]
```diff
@@ -95,7 +95,7 @@ export async function tipUser(
         unsub();
       }
     });
-
+  await api.disconnect();
```
Comment (mordamax) [inline src/tip.ts:98]: does this solve the reconnection or runtime upgrade issue?

File: src/bot.ts [hunk 2]
```diff
@@ -41,8 +41,19 @@ const onIssueComment = async (
...
+    contributorAccount = parseContributorAccount(pullRequestBody);
+  } catch (error) {
+    return error.message;
+  }
+
+  let tipSize: string;
+  try {
+    tipSize = getTipSize(tipSizeInput);
+  } catch (error) {
+    return error.message;
```
Comment (mordamax) [inline src/bot.ts:55]: That covers only these 2 methods, but it doesn't for example `tipUser` or anything else.
I would propose to look into how `respondOnResult` writes the message in ALL cases, and make sure the trace isn't printed there

File: src/tip.ts (hunk 1 above)
Comment (parutger) [reply src/tip.ts:98]: No, But I am hoping this will solve the memory leak issue that was reported.
